// Sequencer gets the transaction from one or more sequence, So we have to differentiate the sequence which is an object that contains 
// a task for generating stimulus. And the sequencer which controls the flow of uvm sequence item transaction generated by one or more sequence.
// Sequencer arbitrates transactions generates by one or more sequences.
// Sequencer sends transactions to driver through a TLM connection and unlike the sequence the sequencer has a fixed location in hierarchy
// A sequencer can be considered a pipe that connects driver and sequence